---
- name: Configure network
  become: true
  lineinfile:
    path: /etc/network/interfaces
    line: '      dns-nameservers 8.8.8.8'
  notify: Restart networking

- name: Install extra packages
  become: true
  apt:
    name: '{{ item }}'
    state: latest
  with_items: '{{ server.packages }}'
  when: server.packages is defined

- name: Configure the timezone
  become: true
  template:
    src: timezone
    dest: /etc/timezone

- name: Configure the timezone
  become: true
  file:
    src: '/usr/share/zoneinfo/{{ server.timezone }}'
    path: /etc/localtime
    state: link
    force: yes

- name: Set default system language pack
  become: true
  locale_gen:
    name: '{{ server.locale }}'

- name: Enable forward agent
  become: true
  lineinfile:
    path: '/etc/ssh/ssh_config'
    regexp: '#(\s*)ForwardAgent.*'
    line: ' \1ForwardAgent yes'
    backrefs: yes

- import_tasks: swap.yml
- import_tasks: links.yml
- import_tasks: ssl.yml
