doctrine:
    dbal:
        url: '%env(DATABASE_URL)%'
        charset: UTF8
        schema_filter: /^(messenger_messages|migration_versions)$/
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
