twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes:
        - '@SonataMedia/Form/media_widgets.html.twig'
        - '@SonataCore/Form/datepicker.html.twig'
        - sonata/custom_widgets.html.twig
    globals:
        xDefaultLocale: '%x_default_locale%'
        gtmId: '%env(GTM_ID)%'
        cookiesDefaultDomain: '%env(COOKIES_DEFAULT_DOMAIN)%'
