services:
    runroom.static_page.admin.static_page:
        class: Runroom\StaticPageBundle\Admin\StaticPageAdmin
        arguments: [~, Runroom\StaticPageBundle\Entity\StaticPage, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Static pages' }
