archetype_demo:
    resource: '@ArchetypeDemoBundle/Resources/config/routing.yaml'

runroom_cookies:
    resource: '@RunroomCookiesBundle/Resources/config/routing.yaml'

# Must be the last one
runroom_static_page:
    resource: '@RunroomStaticPageBundle/Resources/config/routing.yaml'
