---
- name: Install Apache
  sudo: yes
  apt:
    pkg: apache2
    state: latest

- name: Install Apache Modules
  apache2_module:
    state: present
    name: {{ item }}
  notify: restart apache
  with_items:
    - rewrite
    - vhost_alias
    - headers
    - expires
    - filter

- shell: apache2 -v
  register: apache_version

- name: Change default apache site
  sudo: yes
  template:
    src: vhost.conf.tpl
    dest: /etc/apache2/sites-available/000-default.conf
  notify: restart apache
