---
- name: Add ppa repository
  apt_repository:
    repo: ppa:ondrej/apache2

- name: Install Apache
  apt:
    pkg: '{{ item }}'
    state: latest
  with_items:
    - apache2

- name: Install Apache modules
  apache2_module:
    state: present
    name: '{{ item }}'
  notify: Restart Apache
  with_items:
    - actions
    - rewrite
    - vhost_alias
    - headers

- name: Add ServerName to apache.conf
  lineinfile:
    dest: /etc/apache2/apache2.conf
    state: present
    line: 'ServerName localhost'

- name: Change default Apache site
  template:
    src: vhost.conf
    dest: /etc/apache2/sites-available/000-default.conf
  notify: Restart Apache
