---
- name: Add ppa repository
  apt_repository:
    repo: ppa:brightbox/ruby-ng

- name: Install ruby
  apt:
    pkg: 'ruby{{ ruby.version }}'
    state: latest

- name: Symlink exists for ruby
  file:
    src: '/usr/bin/ruby{{ ruby.version }}'
    dest: /usr/local/bin/ruby
    state: link

- name: Symlink exists for ruby gems
  file:
    src: '/usr/bin/gem{{ ruby.version }}'
    dest: /usr/local/bin/gem
    state: link

- name: Install gems
  gem:
    name: '{{ item }}'
    state: latest
    user_install: no
  with_items: '{{ ruby.gems }}'
