imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    # Sonata conf
    - { resource: sonata/sonata_admin.yml }
    - { resource: sonata/sonata_block.yml }
    - { resource: sonata/sonata_media.yml }
    - { resource: sonata/sonata_doctrine_orm_admin.yml }
    # FOS conf
    - { resource: fos/fos_user.yml }

services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

parameters:
    locale: en

framework:
    # esi: ~
    translator:
        fallback: %locale%
    secret: %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation:
        enable_annotations: true
    templating:
        engines: ['twig']
    default_locale: %locale%
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: ~
    fragments: ~
    http_method_override: true

# Twig Configuration
twig:
    debug: "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
       resources:
           - 'SonataMediaBundle:Form:media_widgets.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        server_version: 5.6
        host: "%database_host%"
        port: "%database_port%"
        dbname: "%database_name%"
        user: "%database_user%"
        password: "%database_password%"
        charset: UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager: default
        entity_managers:
            default:
                auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host: "%mailer_host%"
    username: "%mailer_user%"
    password: "%mailer_password%"
    spool:
        type: memory

# Doctrine Behaviors Configuration
knp_doctrine_behaviors:
    translatable: true
    timestampable: true

# A2lix Translation Form Configuration
a2lix_translation_form:
    locales: [es, en]
    default_locale: en
    required_locales: [en]

# Ivory CK Editor Configuration
ivory_ck_editor:
    default_config: config
    configs:
        config:
            toolbar: [ ['Bold', 'Italic', 'Underline'], '-', ['Link', 'Unlink', 'Anchor'], '-', ['NumberedList', 'BulletedList', 'Blockquote'], '-', ['Source'] ]

# Stof Doctrine Extensions Configuration
stof_doctrine_extensions:
    orm:
        default:
            sortable: true
            sluggable: true

# Pix Sortable Behavior Configuration
pix_sortable_behavior:
    position_field:
        default: position
