parameters:
    database_host: 127.0.0.1
    database_port: null
    database_name: {{ mysql.database }}
    database_user: {{ mysql.user }}
    database_password: {{ mysql.password }}

    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null

    secret: {{ symfony.secret }}

    locale: en
    locales: [en, es]

    assets_version: 1.0.0
