---
- name: Create symfony files
  become: false
  template:
    src: '{{ item }}'
    dest: '/tmp/{{ item }}'
  with_items:
    - parameters.yml
    - .htaccess
    - app_dev.php

- name: Move symfony files
  become: false
  command: 'cp /tmp/{{ item.file }} {{ item.dest }}/{{ item.file }}'
  with_items:
    - { file: parameters.yml, dest: /vagrant/app/config }
    - { file: .htaccess, dest: /vagrant/web }
    - { file: app_dev.php, dest: /vagrant/web }

- include: permissions.yml
