---
- name: Add ppa repository
  apt_repository:
    repo: ppa:ondrej/php

- name: Install php
  apt:
    name: 'php{{ php.version }}'
    state: latest

- name: Install php extensions
  apt:
    name: 'php{{ php.version }}-{{ item }}'
    state: latest
  with_items: '{{ php.extensions }}'
  when: php.extensions is defined
  notify: Restart apache

- name: Install php extras
  apt:
    name: '{{ item }}'
    install_recommends: no
    state: latest
  with_items: '{{ php.extras }}'
  when: php.extras is defined
  notify: Restart apache

- name: Disable xdebug
  command: phpdismod xdebug
  args:
    removes: /etc/php/{{ php.version }}/apache2/conf.d/20-xdebug.ini

- name: Modify settings on apache php.ini
  lineinfile:
    dest: '/etc/php/{{ php.version }}/apache2/php.ini'
    regexp: ';?{{ item.setting }} ?=.*'
    line: '{{ item.setting }} = {{ item.value }}'
  with_items: '{{ php.settings }}'

- name: Modify settings on cli php.ini
  lineinfile:
    dest: '/etc/php/{{ php.version }}/cli/php.ini'
    regexp: ';?{{ item.setting }} ?=.*'
    line: '{{ item.setting }} = {{ item.value }}'
  with_items: '{{ php.settings }}'
