---
- name: Add ppa repository
  become: true
  apt_repository:
    repo: ppa:ondrej/php

- name: Install php
  become: true
  apt:
    name: 'php{{ php.version }}-fpm'
    state: latest

- name: Install php extensions
  become: true
  apt:
    name: 'php{{ php.version }}-{{ item }}'
    state: latest
  with_items: '{{ php.extensions }}'
  when: php.extensions is defined
  notify: Restart fpm

- name: Create symbolic link
  become: true
  file:
    src: '/usr/bin/php{{ php.version }}'
    path: /usr/bin/php
    state: link
    force: true

- name: Disable xdebug
  become: true
  command: phpdismod xdebug
  args:
    removes: '/etc/php/{{ php.version }}/fpm/conf.d/20-xdebug.ini'
  notify: Restart fpm

- name: Modify settings on php.ini
  become: true
  lineinfile:
    path: '/etc/php/{{ php.version }}/{{ item[0] }}/php.ini'
    regexp: ';?{{ item[1].setting }} ?=.*'
    line: '{{ item[1].setting }} = {{ item[1].value }}'
  with_nested:
    - [fpm, cli]
    - '{{ php.settings }}'
  notify: Restart fpm

- name: Modify settings on fpm www.conf
  become: true
  lineinfile:
    path: '/etc/php/{{ php.version }}/fpm/pool.d/www.conf'
    regexp: ';?{{ item.setting }} ?=.*'
    line: '{{ item.setting }} = {{ item.value }}'
  with_items: '{{ php.fpm }}'
  notify: Restart fpm
