---
- name: Database migrations
  command: php bin/console doctrine:migrations:migrate --no-interaction
  args:
    chdir: /vagrant
  tags:
    - migrations

- name: Add bash aliases
  template:
    src: .bash_aliases
    dest: '{{ ansible_env.HOME }}/.bash_aliases'

- name: Modify path
  lineinfile:
    dest: '{{ ansible_env.HOME }}/.bashrc'
    state: present
    line: 'export PATH=/vagrant/bin:{{ ansible_env.HOME }}/vendor/bin:{{ ansible_env.HOME }}/.config/composer/vendor/bin:$PATH'

- name: Open on /vagrant by default
  lineinfile:
    dest: '{{ ansible_env.HOME }}/.bashrc'
    state: present
    line: 'cd /vagrant'
