---
- name: Import the yarn gpg key into apt
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present

- name: Add yarn deb repository
  apt_repository:
    repo: 'deb http://dl.yarnpkg.com/debian/ stable main'
    state: present

- name: Install yarn
  apt:
    name: yarn
    state: latest
