---
- hosts: all
  vars_files:
    - vars.yml
  roles:
    - server
    - php
    - phpmyadmin
    - { role: apache, when: webserver.type == 'apache' }
    - { role: nginx, when: webserver.type == 'nginx' }
    - mysql
    - symfony
    - composer
    - node
    - app
