---
server:
  packages: [zip, sqlite3, mailutils, libpng16-16]
  timezone: Europe/Madrid
  locale: es_ES.UTF-8
  swap_size: 2048M
  swap_settings:
    - { key: vm.swappiness, value: 10 }
    - { key: vm.vfs_cache_pressure, value: 50 }
  links:
    - { folder: vendor, dest: /vagrant }
    - { folder: node_modules, dest: /vagrant }
    - { folder: cache, dest: /vagrant/var }
    - { folder: logs, dest: /vagrant/var }
webserver:
  type: nginx
  name: symfony.local
  aliases: []
  root: /vagrant/web
apache:
  modules: [rewrite, ssl, http2, headers, expires, proxy_fcgi]
mysql:
  database: symfony
  user: symfony
  password: symfony
  dump: ''
php:
  version: 7.1
  extensions: [intl, mcrypt, curl, mysql, sqlite3, gd, xml, zip, mbstring, bz2, xdebug, apcu]
  settings:
    - { setting: date.timezone, value: Europe/Madrid }
    - { setting: opcache.enable, value: 1 }
    - { setting: opcache.revalidate_path, value: 1 }
    - { setting: opcache.max_accelerated_files, value: 20000 }
    - { setting: opcache.validate_timestamps, value: 1 }
    - { setting: realpath_cache_size, value: 5M }
    - { setting: realpath_cache_ttl, value: 7200 }
    - { setting: upload_max_filesize, value: 20M }
    - { setting: post_max_size, value: 20M }
  fpm:
    - { setting: pm.max_children, value: 50 }
    - { setting: pm.start_servers, value: 5 }
    - { setting: pm.min_spare_servers, value: 5 }
    - { setting: pm.max_spare_servers, value: 5 }
symfony:
  secret: c81e356a07607848a59e492f824b3fc3bbe61542
  permission_dirs: [cache, logs]
  files:
    - { file: parameters.yml, dest: /vagrant/app/config }
composer:
  packages:
    - { package: hirak/prestissimo }
node:
  source: 6.x
