services:
    runroom.base.admin.meta_information:
        class: Runroom\BaseBundle\Admin\MetaInformationAdmin
        public: true
        arguments: [~, Runroom\BaseBundle\Entity\MetaInformation, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'SEO' }

    runroom.base.admin.entity_meta_information:
        class: Runroom\BaseBundle\Admin\EntityMetaInformationAdmin
        public: true
        arguments: [~, Runroom\BaseBundle\Entity\EntityMetaInformation, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Entity SEO' }
