services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $locales: '%locales%'

    Runroom\BaseBundle\:
        resource: ../../*

    Runroom\BaseBundle\Controller\:
        resource: ../../Controller
        public: true
        tags: [controller.service_arguments]

    Runroom\BaseBundle\Service\MailService:
        bind:
            $from: '%env(MAILER_FROM)%'
            $bcc: '%env(json:MAILER_BCC)%'

    Runroom\BaseBundle\Service\MetaInformation\MetaInformationService:
        bind:
            $providers: !tagged base.meta_information

    Runroom\BaseBundle\Service\AlternateLinks\AlternateLinksService:
        bind:
            $providers: !tagged base.alternate_links

    Runroom\BaseBundle\Service\PageRendererService:
        bind:
            $pageViewModel: '@runroom.base.page_view_model'

    runroom.base.page_view_model: ~
