---
- name: Install phpmyadmin
  apt:
    name: phpmyadmin
    install_recommends: no
    state: latest

- name: Add phpmyadmin to apache
  lineinfile:
    dest: /etc/apache2/apache2.conf
    state: present
    line: 'Include /etc/phpmyadmin/apache.conf'
  notify: Restart apache
