- name: Download composer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer

- name: Install composer
  command: php /tmp/composer-installer --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer

- name: Install global composer packages
  become: false
  command: "composer global require {{ item.package }}:{{ item.version|default('@stable') }}"
  with_items: '{{ composer.packages }}'
  when: composer.packages is defined

- name: Add composer global packages to path
  become: false
  lineinfile:
    dest: '/home/{{ ansible_user }}/.bashrc'
    state: present
    line: 'export PATH=/home/{{ ansible_user }}/.config/composer/vendor/bin:$PATH'

- name: Install composer vendors
  become: false
  composer:
    no_dev: no
    optimize_autoloader: yes
    working_dir: /vagrant
