backoffice:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'

_sonata_admin:
    resource: .
    type: sonata_admin

sonata_user_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml'
    prefix: /resetting

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media
